### ISSUE TITLE
How to show View Details?

### ISSUE THREAD

**Issue by ecotechie** [FacetWP/github-updater-lite#19] opened 2019-01-15 22:59 UTC
I have tags setup:
![image](https://user-images.githubusercontent.com/11607383/51215475-e4f6f000-18d5-11e9-983e-41cd169eb7bd.png)
The update process works. But the View Details link never shows...

I KNOW I'm being dense and this is an easy fix, but I can't seem to find the answer...

**Comment by blogtutor** [comment] 2019-01-17 23:26
@mgibbs189 @afragen Hey guys! I'm stuck on this problem too.

The "View Details" link is not showing up in the plugin list. As far as I can tell, we've got all the required info, and we've updated Github Updater Lite to the August release which was supposed to fix this issue.

Are there any tricks to getting the "View Details" link to show up? Thanks!

![image](https://user-images.githubusercontent.com/24479276/51355487-2de0ad00-1a6c-11e9-8311-e71981e6193c.png)

**Comment by mgibbs189** [comment] 2019-01-17 23:54
@ecotechie @blogtutor The lib doesn't retrieve version details. This is intentional.

I know it sounds silly, but it's because it requires an additional API call for each plugin/theme check. Since GitHub only allows 60 requests/hr for unauthenticated users, many sites would quickly hit this limit.

Here's an example of the API endpoint that this lib uses (hint: it doesn't include version details): https://api.github.com/repos/leongersen/noUiSlider/tags

**Comment by blogtutor** [comment] 2019-01-18 00:06
Hey @mgibbs189 thanks for chiming in.

So we're not seeing the "View Details" link on the update details (per screenshot above). And, when there is an update available, it'll say something like "View Version 0.3 Details."  But when the user clicks on that link, it opens the modal window and then just shows an error.

Since Github Updater Lite has code that looks like it's supposed to handle the View Details, at least in some capacity, I'm scratching my head.  We're not getting any of this showing up.

This is the code I'm looking at in the updater:

```
/**
         * Get plugin info for the "View Details" popup
         *
         * $args->slug = "edd-no-logins"
         * $plugin_path = "edd-no-logins/edd-no-logins.php"
         */
        function plugins_api( $default = false, $action, $args ) {
            if ( 'plugin_information' == $action ) {
                foreach ( $this->update_data as $plugin_path => $info ) {
                    if ( $info['slug'] == $args->slug ) {
                        return (object) array(
                            'name'          => $info['name'],
                            'slug'          => $info['slug'],
                            'version'       => $info['new_version'],
                            'download_link' => $info['package'],
                            'sections' => array(
                                'description' => $info['description']
                            )
                        );
                    }
                }
            }
            return $default;
        }

```

So even if it doesn't show info pertaining to the current version (or an available update), we are trying to get it to show *something* -- even if that means it's just a link to a changelog that's hosted elsewhere.

I feel like we either must be missing something super-simple in our setup, or we've hit a bug.

**Comment by mgibbs189** [comment] 2019-01-18 00:21
@blogtutor Does your plugin / theme have a `Description` set? E.g. https://d.pr/i/6jGmMe

Because that's what I *think* should show up in the `View version {n} details` box. If not, then it's probably a bug.

**Comment by afragen** [comment] 2019-01-18 00:23
It's not a bug. That function doesn't exist in this code. Here's the relevant code from GitHub Updater.

https://github.com/afragen/github-updater/blob/ebc29f489aae2bd0caf1e0e59c7fd9a89403ca78/src/GitHub_Updater/Plugin.php#L226

https://github.com/afragen/github-updater/blob/ebc29f489aae2bd0caf1e0e59c7fd9a89403ca78/src/GitHub_Updater/Plugin.php#L289-L328

**Comment by blogtutor** [comment] 2019-01-18 00:24
Yep:
```
/**
 * Plugin Name: NerdPress Support
 * Description: Adds the NerdPress support widget to your WordPress dashboard for easy access to our knowledge base and contact form.
 * Version: 	0.4.3
 * Author:      NerdPress
 * Author URI:  https://www.nerdpress.net
 * GitHub URI: 	blogtutor/blog-tutor-support
 * License: 	GPLv2 or later
 * Text Domain: blog-tutor
 * Domain Path: /languages/
 */
```

We also tried adding a Plugin URI (to our Github Repo), which didn't help (It did add the "Visit plugin site" link, though!).

**Comment by blogtutor** [comment] 2019-01-18 00:30
Thanks Andy.  So I'm confused as to what the section of code in the Lite plugin that I quoted above ("Get plugin info for the "View Details" popup") is supposed to do?

**Comment by afragen** [comment] 2019-01-18 00:38
It populates the data for the _View version x.x.x details_ link when there is an update available.

**Comment by afragen** [comment] 2019-01-18 00:41
I'm actually not certain it takes any additional API calls to get this info. I think it comes from the _plugins_api_ filter hook.

But @mgibbs189 would need to add the code I cited above. Without API calls to get more information, I'm not sure how much benefit that would add.

**Comment by blogtutor** [comment] 2019-01-18 00:46
Hang on a sec! We found the source of our confusion.

It seems the regular "View Details" link will only show up when an update is available (so the "View version x.x.x details" link is also there).  So we either get both links, or neither.

We were testing without an update available, just trying to get the regular "View Details" link to show... It was only when we lowered the version number on our test site (to make the update show up), that BOTH show up!

**Comment by mgibbs189** [comment] 2019-01-18 02:40
> I'm actually not certain it takes any additional API calls to get this info.

@afragen are you referring to the "changelog" (i.e. tag description)? If so, I don't see another way without (a) another API call, or (b) switching to the GitHub API v4 (GraphQL)

**Comment by afragen** [comment] 2019-01-18 02:57
Matt, I was referring to the current data that is displayed when the _View version x.x.x details_ is displayed. I believe added the hook and a modified version of the function referenced should produce a _View Details_ link even when an update is not available. That iframe isn’t going to have much data.

You are correct that more information will require more API calls. Obviously GitHub Updater makes these API calls for this purpose, but this is supposed to be _GitHub Updater Lite_. 😉

**Comment by mgibbs189** [comment] 2019-01-18 03:10
@afragen makes sense, thanks.

FYI, turns out that the v4 API is pretty powerful 😄 

```graphql
{
  repository(owner: "facetwp", name: "facetwp-map-facet") {
    tags: refs(refPrefix: "refs/tags/", last: 1) {
      edges {
        tag: node {
          name
          target {
            ... on Tag {
              tagger {
                name
                email
                date
              }
              message
            }
          }
        }
      }
    }
  }
  rateLimit {
    limit
    cost
    remaining
    resetAt
  }
}
```

The above GraphQL counts as 1 request, and retrieves the following:

* The latest tag name
* The author email / name
* The tag message (changelog?)
* The tag date
* All rate limit information

Playground: https://developer.github.com/v4/explorer/

**Comment by blogtutor** [comment] 2019-01-18 03:22
Oh! I see you guys are on the case! Awesome.

It seems you are way ahead of me, and this is tangentially related, but:  I just modified the script to pull the changelog directly from the Github API and parse it nicely so it'll show in the "View version x.x.x. details" Modal Window.  I know this is another API request, so it's not ideal. I've set up a fallback at least, so if the request fails, it'll show a link to the release notes page instead.

Not sure if you'd want to use this in the codebase, but I'm happy to share it if you think it could be helpful.. 

![image](https://user-images.githubusercontent.com/24479276/51363493-19f97300-1a8d-11e9-95ad-e60dd92e89c2.png)

**Comment by afragen** [comment] 2019-01-18 03:35
@mgibbs189 I haven’t played with GitHub API v4 before. Looks powerful, but also looks like I would need to rewrite all the parsing code. 🤔

@blogtutor at some point you may want to look into the the non-lite version. 😉

**Comment by blogtutor** [comment] 2019-01-18 03:37
@afragen Haha! The thing is, I love not having to install a separate plugin.  :)

**Comment by afragen** [comment] 2019-01-18 03:40
@blogtutor that’s why Matt created this library.

@mgibbs189 it looks like v4 requires an oAuth token. That’s not something I’ve figured out how to get or use — yet. It’s on my list.

**Comment by mgibbs189** [comment] 2019-01-18 13:50
@afragen Yeah, good catch. Not having a quota (even a small one) for unauthenticated requests makes v4 a dealbreaker 😦

**Comment by mgibbs189** [comment] 2019-01-21 21:14
Closing for now. The v4 api requires auth, which is a non-starter for this lib.

**Closed as completed by mgibbs189** 2019-01-21 21:14 UTC

**Comment by blogtutor** [comment] 2019-01-21 21:16
@mgibbs189 Hey Matt - The "View Details" link still only shows up if an update is available - so perhaps this issue should stay open until that's resolved?
